config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :tasks
  resources :users
  #friend routing
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
# listing all tasks and current user tasks
  get '/users/index' => 'users#index'
  get '/usertasks' => 'tasks#listuser'

  get 'pages/help'
  get 'pages/contact'

# these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'


end

app/models/task.rb
class Task < ApplicationRecord
belongs_to :user
  validates :title, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  # FIXME ajax should be working with create and destroy actions
  # GET /tasks
  # GET /tasks.json
  def index
    @user = current_user
    @tasks = @user.tasks.all.order(:priority).paginate(:page => params[:page], :per_page => 5)
    @task = Task.new

  end

  def listuser
    @tasks = Task.where(:user_id => current_user).order(:priority)
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :priority, :user_id, :due_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true, class: 'ui form' do |t| %>
       <div class="two fields">
        <div class="required field">
         <strong> <%= t.label :title %>:</strong>
          <%=t.text_field :title %>
        </div><br />

          <div class="field">
           <strong><%= t.label :priority %>:</strong>
            <em style="color:red;">Highest</em> <%=t.range_field :priority, in: 1..10 %> <em style="color:green;">Lowest</em>
          </div><br />
       </div>
          <div class="field">
            <strong><%= t.label :due_date %>:</strong>
            <%=t.datetime_field :due_date %>
       </div><br />

          <div class="field">
           <strong> <%= t.label :description %>:</strong>
            <%=t.text_area :description%>
          </div><br />
  <div class="actions">
    <%= link_to 'Cancel', tasks_path, class: 'ui basic negative button' %>
    <%= t.submit class: 'ui basic positive button', remote: true %>
  </div>
<%end%>

<script>
    $('.ui.form')
        .form({
            fields: {
                title: {
                    identifier: 'title',
                    rules: [
                        {
                            type: 'empty',
                            prompt: 'Please enter a task title'
                        }
                    ]
                }
            }})
    ;
</script>

app/views/tasks/create.js.erb
$('#incomplete_tasks').append('<%= j render(@task) %>')

app/views/tasks/destroy.js.erb
$(document).on('tubtolinks:load', function () {
      $('#delete_task').closest('tr').fadeOut(1500);
});

app/views/tasks/edit.html.erb
<div class="ui grid">
  <div class="two wide column"></div>
  <div class="eight wide column">

<div class="ui container">
<br>
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
</div>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

  </div>

</div>

app/views/tasks/index.html.erb
<%= render 'shared/submenu' %>

<h1 id="center">Tasks for <%=link_to current_user.display_name, current_user %> </h1>
<br />
<% if @task.errors.any? %>
    <div class="ui error message" id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being created:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            </ul>
            </div>
        <% end %>
<% end %>
<div id='incomplete_tasks'>
<table class="ui sortable celled table">
  <thead class="full width">
    <tr>
      <th>Created by</th>
      <th>Task</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Created on</th>
      <th class="sorted descending">Due by</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr id='<%=task.id%>'>
        <td><%= task.user.display_name%></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.created_at.strftime("%b %d, %Y") %></td>
        <% if task.due_date.present? %>
        <td><%= distance_of_time_in_words(task.due_date, Time.now) %></td>
            <%else%>
            <td>Not Specified</td>
            <%end%>
        <td class="positive"><%= link_to 'View', task %></td>
        <td class="warning"><%= link_to 'Edit', edit_task_path(task) %></td>
        <td class="negative"><%= link_to 'Remove', task, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, id: 'delete_task' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

<div class='ui grid'>
  <div class='six wide column'>
    <!-- START MODAL -->
    <%=link_to 'New Task', new_task_path, id: 'new_link', class: 'ui primary button', remote: true %>
    <div class="ui small modal" id="task_modal">
      <i class="close icon"></i>
      <div class="header">Add Task</div>
      <div class="content">
       <%= render 'form' %>
      </div>
    </div>
    </div>
    <!-- END MODAL -->
</div>
<br />
<div class="center" id="apple_pagination">
  <% if @tasks.count > 5 %>
      <%= will_paginate @collection, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
  <%else%>
  <%="Page 1 of 1" %>
  <%end%>
</div>

<script>
    $(function() {
        $('table').tablesort()
    });
</script>

app/views/tasks/listuser.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1 id="center">Tasks for <%=link_to current_user.display_name, current_user %> </h1>

<table class="ui celled table" class="ui table">
  <thead class="full width">
    <tr>

      <th class="three wide">Task</th>
      <th class="six wide">Description</th>
      <th class="one wide">Priority</th>
      <th class="two wide">Created at</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>

        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.created_at.strftime("%b %d, %Y") %></td>
        <td class="info"><%= link_to 'Open', task %></td>
        <td class="warning"><%= link_to 'Edit', edit_task_path(task) %></td>
        <td class="positive"><%= link_to 'Complete', task, method: :delete, data: { confirm: 'Are you sure you have completed this task?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="ui buttons">
<%= link_to 'New Task', new_task_path, class: 'ui primary button', id: 'new_task', remote: true %>
<div class="or"></div>
<%= link_to 'All Tasks', tasks_path, class: 'ui secondary button' %>
</div>

app/views/tasks/new.html.erb
<div class="ui container">
<br>
  <% if @task.errors.any? %>
      <div class="ui error message" id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being created:</h2>

        <ul>
          <% @task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              </ul>
              </div>
          <% end %>
  <% end %>
<h1>New Task</h1>
<%= render 'form' %>
</div>
<br>

app/views/tasks/new.js.erb
// $('#new_link').hide().after('<%= j render('form')%>');

app/views/tasks/show.html.erb
<br>


<div class="ui container">

  <table class="ui celled table">
  <thead>
    <tr><th>Title:</th>
    <th>Priority:</th>
    <th>Description:</th>
    <th>Created By:</th>
  </tr></thead>
  <tbody>
    <tr>
      <td>
       <%= @task.title %>
      </td>
      <td><%= @task.priority %></td>
      <td><%= @task.description %></td>
      <td><%= @task.user.display_name %></td>
    </tr>

  </tbody>
</table>


<br>
<div class="ui buttons">
<%= link_to 'Edit', edit_task_path(@task), class: 'ui secondary button' %>
<div class="or"></div>
<%= link_to 'All Tasks', tasks_path, class: 'ui button' %>
</div>
</div>