config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :tasks
  resources :users
  #friend routing
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
# listing all tasks and current user tasks
  get '/users/index' => 'users#index'
  get '/usertasks' => 'tasks#listuser'

  get 'pages/help'
  get 'pages/contact'

# these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy

  def index
    if params[:search]
    @friends = current_user.friends.find(:conditions => ['name LIKE?', "%#{params[:search]}%"])
    else
      @friends = current_user.friends.all
    end

  end

  def destroy
    current_user.remove_friend(@friend)
    flash[:notice]= "Friend successfully removed"
    redirect_to friends_path

  end

  private

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/views/friends/_list.html.erb
<%= form_tag friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <a class="ui item">
      <div class="ui icon input">
        <%= text_field_tag :search,

                           params[:search],

                           placeholder: 'Name or Email',

                           autofocus: true,

                           class: 'ui small icon input' %>
        <%= button_tag(type: :submit, class: 'ui tiny basic primary button') do %>

            <i class='fa fa-search'></i> Search friends

        <% end %>
      </div>
    </a>
    </div>
    </div>
<% end %>
<div class="results" id='friend-lookup-results'>
  <%= render 'shared/spinner' %>
  <% if @users %>
      <% if @users.size > 0 %>
          <h3>Search Results</h3>

          <table class=" ui celled table">
            <% @users.each do |user| %>
                <thead class="full width">
                <tr>
                  <th class="two wide"><strong>Name:</strong></th>
                  <th class="three wide"><strong>Email:</strong></th>
                  <th colspan="2"><strong>Profile:</strong></th>
                  <th class="two wide"><strong>Add:</strong></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td><%= user.display_name %></td>
                  <td><%= user.email %></td>
                  <td><%= link_to "View Profile", user_path(user), class: "ui basic button success" %></td>
                  <% if current_user.not_friends_with?(user.id) %>
                      <td><%= link_to "Add friend", add_friend_path(user: current_user, friend: user),

                                      class: 'ui tiny basic success button', method: :post %></td>
                  <% else %>
                          <span class='label label-primary'>
                            You are friends
                          </span>
                      </tr>
                      </tbody>
                      </table>
                  <% end %>
            <% end %>
            </div>
      <% else %>
          <div class="ui raised segment">
            <p> Sorry, no users matched your search </p>
          </div>
      <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
  <br />

app/views/friends/index.html.erb
<%= render 'shared/submenu' %>

<div class='twelve wide column' id='friend-lookup-results'>

  <table class="ui celled table">
    <thead class="full width">
    <tr>
      <th colspan="5" class="page-header">
        <h2 align='center'>My Friends</h2>
      </th>
    </tr>
    <tr align='center'>
      <th class="two wide">Friend</th>
      <th class="two wide">Email</th>
      <th class="three wide">Friends since</th>
      <th colspan="2">Actions</th>
    </tr>
    </thead>
    <tbody>
      <%@friends.each do |friend| %>
          <tr>
            <td><%= friend.display_name%></td>
            <td><%= friend.email %></td>
            <td><%= friend.created_at.strftime("%b %d, %Y")%></td>
            <td>
              <%= link_to "View Profile", user_path(friend), class: "ui basic positive button" %></td>
            <td> <%= link_to 'Remove Friend',

                             friend_path(friend),

                             :method => :delete,

                             :data => { :confirm => 'Are you sure?' },

                             :class => 'ui basic negative button' %>
            </td>
          </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div id="friend-lookup-errors"></div>
<br>
<div class="center" id="apple_pagination">
  <% if @friends.count > 5 %>
      <%= will_paginate @collection, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
  <%else%>
      <%="Page 1 of 1" %>
  <%end%>
</div>
    <br>