config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :tasks
  resources :users
  #friend routing
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
# listing all tasks and current user tasks
  get '/users/index' => 'users#index'
  get '/usertasks' => 'tasks#listuser'

  get 'pages/help'
  get 'pages/contact'

# these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'


end

app/views/layouts/_footer.html.erb
<!-- ##/// Footer ///## -->
<div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
      <div class="ui stackable inverted divided grid">
        <div class="three wide column">
          <h5 class="ui inverted header">Action Links</h5>
          <div class="ui inverted link list">
            <a href="#" class="item">One</a>
            <a href="#" class="item">Two</a>
            <a href="#" class="item">Three</a>
          </div>
        </div>
        <div class="three wide column">
          <h5 class="ui inverted header">Group 2</h5>
          <div class="ui inverted link list">
            <a href="#" class="item">Link One</a>
            <a href="#" class="item">Link Two</a>
            <a href="#" class="item">Link Three</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Created by: Frederick John</h4>
          <div class="ui inverted link list">
            <a href="https://www.linkedin.com/in/frederick-john-444151104" target="_blank">
            <button class="tiny ui linkedin button" id="socialink">
              <i class="linkedin icon"></i>
             LinkedIn
            </button></a>
            <a href="https://www.youtube.com/channel/UCV9peDAcHi2WOSEkghABzJw" target="_blank">
            <button class="tiny ui youtube button" id="socialink">
              <i class="youtube icon"></i>
              YouTube
            </button></a>
            <a href="https://twitter.com/FiatCrisis" target="_blank">
            <button class="tiny ui twitter button" id="socialink">
              <i class="twitter icon"></i>
              Twitter
            </button></a>
          </div>
        </div>
        <div class="seven wide column">
          <h5 class="ui inverted header">Swiftlabs Inc.</h5>
          <p>Brought to you by the creator Fierce Momentum™</p>
          <p>Made with ♥ in Philadelphia</p>
        </div>
      </div>
      <div class="ui inverted section divider"></div>
      <%=image_tag 'check-mark.png', class: "ui centered mini image"%>
      <div class="ui horizontal inverted small divided link list">
        <a class="item" href="#">Site Map</a>
        <a class="item" href="mailto:swiftlabs.space">Contact Us</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
      </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<div class="ui fixed inverted menu">
    <div class="ui container">
    <div class="header item" id="brand">
      <%=link_to image_tag('check-mark.png', size: "36x36"), root_path, class: "ui centered mini image"%>
      <%= link_to 'Swiftly', root_path%>
    </div>

      <%= link_to ' Contact ', pages_contact_path, class: "header item" %>
      <%= link_to ' Help ', pages_help_path, class: "header item" %>

    </div>
    <div class="right menu">
      <% if current_user %>

      <%=link_to current_user.display_name, current_user, class: "header item" %>
     
       <%= link_to "Logout", '/logout', class: "header item" %>
       <% else %>
       <%= link_to 'Login', '/login', class: "header item" %> <%= link_to 'Signup', '/signup', class: "header item" %>
      <% end %>
    </div>
  </div>

app/views/layouts/_user_header.html.erb
<div class="ui fixed inverted menu">
  <div class="ui container">
    <div class="header item" id="brand">
      <%=link_to image_tag('check-mark.png', size: "36x36"), root_path, class: "ui centered mini image"%>
      <%= link_to 'Swiftly', root_path%>
    </div>

    <%= link_to ' Create Task ', new_task_path, class: "header item" %>
    <%= link_to ' Tasks ', tasks_path, class: "header item" %>
    <%= link_to ' All Users ', users_path, class: "header item" %>
    <%= link_to ' Friends ', friends_index_path, class: "header item" %>

  </div>
  <div class="right menu">
    <% if current_user %>

        <%=link_to current_user.display_name, current_user, class: "header item" %>

        <%= link_to "Logout", '/logout', class: "header item" %>
    <% else %>
        <%= link_to 'Login', '/login', class: "header item" %> <%= link_to 'Signup', '/signup', class: "header item" %>
    <% end %>
  </div>
</div>
<br />

app/views/layouts/application.html.erb
<!doctype html>
<html>
    <head>
        <title>Swiftly</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Lato|Lora|Raleway" rel="stylesheet">
        <script src="https://use.fontawesome.com/270c98753c.js"></script>
    </head>

    <body>
        <div class="ui container">
        <%=render 'layouts/header'%>
        <br />
        <br />
        <%if !flash[:notice].blank? %>
        <div class="notice">
            <p class="ui positive message"><%= flash[:notice]%></p>
        </div>
        <%end%>
        <br />
        <%if !flash[:error].blank? %>
        <div class="error">
            <p class="ui negative message">
                <%= flash[:error]%></p>
        </div>
        <%end%>

        <%= yield %>
    </div>
        <br />
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/layouts/user.html.erb
<!doctype html>
<html>
<head>
  <title>Swiftly</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Lato|Lora|Raleway" rel="stylesheet">
  <script src="https://use.fontawesome.com/270c98753c.js"></script>
</head>

<body>
<div class="ui container">
  <%=render 'layouts/user_header'%>
  <br />
  <br />
  <%if !flash[:notice].blank? %>
      <div class="notice">
        <p class="ui positive message"><%= flash[:notice]%></p>
      </div>
  <%end%>
  <br />
  <%if !flash[:error].blank? %>
      <div class="error">
        <p class="ui negative message">
          <%= flash[:error]%></p>
      </div>
  <%end%>
  <br />
  <%= yield %>
</div></div>
<br />
<%= debug(params) if Rails.env.development? %>
<%= render 'layouts/footer' %>
</body>
</html>